---
swagger: "2.0"
info:
  description: "API for HIOT.io Thing Devices"
  version: "0.0.1"
  title: "HIOT.io - Thing API"
host: "virtserver.swaggerhub.com"
basePath: "/healyma/HIOT.io.Thing/0.0.1"
schemes:
- "https"
paths:
  /thing/sensor/{sensorId}:
    get:
      tags:
      - "Thing - Sensors"
      summary: "get readings from the specified sensor"
      operationId: "thingSensorSensorIdGET"
      parameters:
      - name: "sensorId"
        in: "path"
        description: "ID of the sensor to read"
        required: true
        type: "string"
      responses:
        200:
          description: "succecss"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/inline_response_200"
        400:
          description: "unknown sensor"
      x-swagger-router-controller: "ThingSensors"
  /thing/controller:
    get:
      tags:
      - "Thing - Controller"
      description: "returns an array of commands"
      operationId: "thingControllerGET"
      parameters: []
      responses:
        200:
          description: "success"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/inline_response_200_1"
      x-swagger-router-controller: "ThingController"
    post:
      tags:
      - "Thing - Controller"
      description: "execute a command"
      operationId: "thingControllerPOST"
      parameters: []
      responses:
        200:
          description: "success"
        400:
          description: "unknown command"
      x-swagger-router-controller: "ThingController"
  /thing/status:
    get:
      tags:
      - "Thing"
      description: "check the status of the thing"
      operationId: "thingStatusGET"
      parameters: []
      responses:
        200:
          description: "success"
          schema:
            $ref: "#/definitions/inline_response_200_2"
        500:
          description: "serious error"
      x-swagger-router-controller: "Thing"
  /thing/sync:
    post:
      tags:
      - "Thing"
      description: "reset elapsed time to zero"
      operationId: "thingSyncPOST"
      parameters: []
      responses:
        200:
          description: "successful resyncing"
      x-swagger-router-controller: "Thing"
  /thing/properties:
    get:
      tags:
      - "Thing"
      operationId: "thingPropertiesGET"
      parameters: []
      responses:
        200:
          description: "success"
          schema:
            $ref: "#/definitions/inline_response_200_3"
      x-swagger-router-controller: "Thing"
definitions:
  inline_response_200_2_memory:
    properties:
      total:
        type: "number"
      available:
        type: "number"
  inline_response_200_1:
    properties:
      cmd:
        type: "string"
        description: "the commandCode"
      description:
        type: "string"
        description: "a human readable description of the command"
  inline_response_200_3_deviceRoles:
    properties:
      roleId:
        type: "string"
      roleName:
        type: "string"
  inline_response_200:
    properties:
      reading:
        type: "string"
      value:
        type: "string"
  inline_response_200_2:
    properties:
      name:
        type: "string"
      uptime:
        type: "number"
      memory:
        $ref: "#/definitions/inline_response_200_2_memory"
      dutyCycle:
        type: "number"
        description: "percentage of time spent gathering data etc."
      frequency:
        type: "number"
        description: "polling frequency in milliseconds"
      lastUpload:
        type: "number"
        description: "seconds elapsed since last successful data transfer to Aggregator"
  inline_response_200_3:
    properties:
      deviceId:
        type: "string"
      deviceRoles:
        type: "array"
        items:
          $ref: "#/definitions/inline_response_200_3_deviceRoles"
